baseURL = "../" 
languageCode = "es-es"
title = "RA-04"
theme = "soho"


[params]
  description = "Un Respirador para el personal de la salud"
  profilePicture = "images/profile.png"
  copyright = "Raul Mera"
  license = "CC BY-SA 4.0"
  licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

[menu]


[[menu.main]]
  name = "Contacto"
  identifier = "contacto"
  weight = 80
  url = "/contacto/"

[[menu.main]]
  name = "Vision"
  identifier = "vision"
  weight = 11
  url = "/vision/"

[[menu.main]]
  name = "Materiales"
  identifier = "materiales"
  weight = 20
  url = "/materiales/"

[[menu.main]]
  name = "Confeccion Respirador"
  identifier = "resp"
  weight = 30
  url = "/resp/"

[[menu.main]]
  name = "Confeccion Filtro"
  identifier = "filtro"
  weight = 40
  url = "/filtro/"

 [[menu.main]]
  name = "Postura del Respirador"
  identifier = "postura"
  weight = 45
  url = "/postura/"
 

[[menu.main]]
  name =  "Discusion"
  identifier = "discusion"
  weight = 60
  url = "/discusion/"

[[menu.main]]
  name = "Links"
  identifier = "links"
  weight = 70
  url = "/links/"



