baseURL = "../" 
languageCode = "es-es"
title = "RA-03"
theme = "soho"


[params]
  description = "Un Respirador para el personal de la salud"
  profilePicture = "images/profile.png"
  copyright = "Raul Mera"
  license = "CC BY-SA 4.0"
  licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

[menu]

[[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 300
  url = "/index"

[[menu.main]]
  name = "6. Contacto"
  identifier = "contacto"
  weight = 300
  url = "/contacto/"

[[menu.main]]
  name = "1. Vision"
  identifier = "vision"
  weight = 300
  url = "/vision/"

[[menu.main]]
  name = "2. Materiales"
  identifier = "materiales"
  weight = 300
  url = "/materiales/"

[[menu.main]]
  name = "3. Instrucciones"
  identifier = "Instrucciones"
  weight = 300
  url = "/instrucciones/"

[[menu.main]]
  name = "4. Discusion"
  identifier = "discusion"
  weight = 300
  url = "/discusion/"

[[menu.main]]
  name = "5. Links"
  identifier = "links"
  weight = 300
  url = "/links/"



